version: '3.4'

services:
  apitesting:
    image: cordfinancetest
    container_name: cordfinancetest
    build: 
        context: src/
        dockerfile: debug.Dockerfile
    command:
      run https://www.getpostman.com/collections/bd9af4efe8967ccdc9ff
      -e ./postman/env.json
      -d ./postman/data2V.json
    networks:
      - cordfinance
    expose:
      - "80"
  
networks:
  cordfinance:
    driver: bridge
